### ISSUE TITLE
Update Docker Hub image

### ISSUE THREAD

**Issue by naorunaoru** [monokal/docker-tinyproxy#15]
https://hub.docker.com/r/dannydirect/tinyproxy hasn't been updated in 2 years. @monokal can you update it?

**Comment by monokal** [comment]
The latest image is building here, I'll update the docs: https://hub.docker.com/repository/docker/monokal/tinyproxy

**Comment by effektsvk** [comment]
If it is possible, could you please update docs on your old docker repo (dannydirect)? It has over 5 milion pulls so it always pops up first and I believe many people choose that image because of that. Luckily, I stumbled upon this issue after using your outdated image for 3 months but only because I had some freezing issue... A large deprecation header in the old repo would be nice :D

**Comment by monokal** [comment]
I've done that now, thanks for the heads up!
